# Generated by Django 5.2.4 on 2025-08-21 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveBigIntegerField()),
                ('muted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chat_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['room_id'], name='notificatio_room_id_00eeb1_idx'), models.Index(fields=['room_id', 'muted'], name='notificatio_room_id_207563_idx'), models.Index(fields=['user', 'room_id'], name='notificatio_user_id_d8a4c2_idx')],
                'unique_together': {('user', 'room_id')},
            },
        ),
    ]
