# Generated by Django 5.2.4 on 2025-08-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='folder',
        ),
        migrations.AddField(
            model_name='chat',
            name='folders',
            field=models.ManyToManyField(related_name='chats', to='chat.folder'),
        ),
    ]
