# Generated by Django 5.2.4 on 2025-07-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='cities',
            field=models.ManyToManyField(related_name='chatrooms', to='chat.city'),
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='city',
        ),
    ]
