# Generated by Django 5.2.4 on 2025-08-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_folder_chat_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#2196F3', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='chats', to='chat.label'),
        ),
        migrations.AddField(
            model_name='folder',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='folders', to='chat.label'),
        ),
    ]
