# Generated by Django 5.2.4 on 2025-08-14 12:47

import chat.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'verbose_name': 'Folder', 'verbose_name_plural': 'Folders'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_room_id_edc775_idx',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='folder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=chat.models._message_upload_to),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('file', 'File')], default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='chat',
            name='folders',
            field=models.ManyToManyField(blank=True, related_name='chats', to='chat.folder'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='label',
            name='color',
            field=models.CharField(default='#7C3AED', max_length=7),
        ),
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='display_name',
            field=models.CharField(blank=True, help_text='Показываемое имя отправителя', max_length=150),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='chat_messag_room_id_5feac5_idx'),
        ),
    ]
