# Generated by Django 5.2.4 on 2025-08-15 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_hiddenmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('is_muted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='is_secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='private_key',
            field=models.CharField(blank=True, help_text='Уникальная пара участников для приватного чата', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='self_destruct_timer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='type',
            field=models.CharField(choices=[('group', 'Групповой'), ('private', 'Личный')], db_index=True, default='group', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', '-created_at'], name='chat_messag_room_id_edc775_idx'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_links', to='chat.chat'),
        ),
        migrations.AddField(
            model_name='chatparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='chats', through='chat.ChatParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['type', '-created_at'], name='chat_chat_type_c0e803_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'chat'], name='chat_chatpa_user_id_c46732_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat', 'user'], name='chat_chatpa_chat_id_069740_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat', 'user')},
        ),
    ]
