# Generated by Django 5.2.4 on 2025-07-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_interests_remove_user_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('moderator', 'Модератор'), ('vip', 'VIP'), ('user', 'Пользователь')], default='user', max_length=16, verbose_name='Роль пользователя'),
        ),
    ]
