# Generated by Django 5.2.4 on 2025-07-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.AlterField(
            model_name='user',
            name='interface_language',
            field=models.CharField(default='en', max_length=20, verbose_name='Язык интерфейса'),
        ),
    ]
