# Generated by Django 5.2.4 on 2025-07-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_language_alter_user_interface_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interface_language',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
