# Generated by Django 5.2.4 on 2025-08-20 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_phone_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('language', models.CharField(default='en', max_length=10)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('auto', 'Auto')], default='dark', max_length=10)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('push_notifications', models.BooleanField(default=True)),
                ('sound_notifications', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=False)),
                ('message_notifications', models.BooleanField(default=True)),
                ('group_notifications', models.BooleanField(default=True)),
                ('profile_visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends'), ('private', 'Private')], default='public', max_length=10)),
                ('online_status', models.BooleanField(default=True)),
                ('read_receipts', models.BooleanField(default=True)),
                ('last_seen', models.BooleanField(default=True)),
                ('auto_download_images', models.BooleanField(default=True)),
                ('auto_download_videos', models.BooleanField(default=False)),
                ('auto_download_documents', models.BooleanField(default=False)),
                ('enter_to_send', models.BooleanField(default=True)),
                ('camera_permission', models.BooleanField(default=True)),
                ('microphone_permission', models.BooleanField(default=True)),
                ('autoplay_videos', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('session_timeout', models.PositiveIntegerField(default=30)),
                ('auto_connect', models.BooleanField(default=True)),
                ('data_usage', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
